name: "Solary-Economy"
main: "com.redeskyller.bukkit.solaryeconomy.SolaryEconomy"
version: "1.5.3"
description: "Um sistema de economia para seu servidor Minecraft."
authors: ["Sr_Edition", "0xflucas"]
softdepend: ["Vault", "LegendChat", "PlaceholderAPI"]
load: "STARTUP"
commands:
  money:
    description: "Para ver o saldo atual"
    aliases: [coin, coins, solaryeconomy]