name: Solary-Economy
main: nuvemplugins.Main
version: 1.2
author: Sr_Edition
website: www.nuvemplugins.com
softdepend: [Vault]
load: STARTUP
commands:
  money:
    description: "Para ver o money atual"
    aliases: [coin, coins, solaryeconomy]
